### ISSUE TITLE
Namespace scoping of CRDs is inferred

### ISSUE THREAD

**Issue by alexzielenski** [kubernetes-sigs/kubectl-validate#16]
Currently we have no way to tell from an OpenAPI schema if a CRD is namespace or cluster scoped, so we infer the scope from the presence of the `metadata.namespace` field. It'd be nice if users could get errors about namespace misuse.

For schemas sourced from local CRDs we have access to this information but do not use it. A small improvement could be to propagate that information, but that would not solve the issue for schemas sourced from OpenAPI/clusters.

**Comment by apelisse** [comment]
@natasha41575 @mortent I think some people have been complaining about the same thing, i.e. there's no way to know from openapi if a type is namespaced or not. Any idea how we can fix this long-term?

**Comment by apelisse** [comment]
Related to https://github.com/kubernetes/enhancements/pull/3938#discussion_r1185579338

**Comment by alexzielenski** [comment]
As a dirty hack I think it might be able to be inferred from OpenAPI spec `Paths` list. If /apis/<group>/<version>/namespaces/{namespace}/<resource>` is listed, then the resource is namespace scoped.

**Comment by apelisse** [comment]
Yes, I think that's the best we've had so far.

**Comment by lauchokyip** [comment]
@alexzielenski @apelisse 

I would like to take on this issue, but I need some guidance after looking into the source code

Observations:
1) Look like the OpenAPI 's Path can be found here
https://github.com/kubernetes-sigs/kubectl-validate/blob/216078149eae94930b88caa666a7eff817febc83/pkg/validatorfactory/factory.go#L262-L270
2) This needs to be changed
https://github.com/kubernetes-sigs/kubectl-validate/blob/216078149eae94930b88caa666a7eff817febc83/pkg/cmd/validate.go#L266-L272

Questions:
1) Where is the best area to add where it can check the path? I feel like doing it in the function `ValidatorsForGVK` won't make much sense but if we were to do it in a new function, we might have to `Unmarshal` and `Marshal` again to openapispec like this
https://github.com/kubernetes-sigs/kubectl-validate/blob/216078149eae94930b88caa666a7eff817febc83/pkg/validatorfactory/factory.go#L262-L270
2) What if it's a file like this (https://github.com/kubernetes-sigs/kubectl-validate/blob/main/testcases/manifests/error_cel_basic.yaml) where it has no openapi defined path?
3) The code looks like it's checking all the path and store them in a map for caching, are we just want to find the one GVK? For example [this file](https://github.com/kubernetes-sigs/kubectl-validate/blob/main/testcases/manifests/error_array_instead_of_map.yaml) would be ConfigMap, so we only need to check for `/api/v1/configmaps` instead of everything ?
https://github.com/mortent/kustomize/blob/d083c7f1d03a5ba8d0dc00ffadda7ac744c8e1df/kyaml/openapi/openapi.go#L433-L456

/assign

**Comment by lauchokyip** [comment]
Thanks @alexzielenski , took a peek at the PR, seem like it was close to what I wanted to do, just missing some pieces. 👍🏻
